appName: lid
namespace: lulo

image:
  repository: docker.yesidlopez.de/lid
  pullPolicy: IfNotPresent
  tag: "2.6"

service:
  type: LoadBalancer
  port: 3000

# Add resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
